name: nodejs-polars-test
on:
  pull_request:
    paths:
      - 'nodejs-polars/**'
jobs: 
  test-js: 
    runs-on: ubuntu-latest
    name: Run lint & tests
    defaults:
      run:
        working-directory: nodejs-polars
    strategy:
      matrix:
        js-version: ["16", "17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.js-version }}
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-02
          override: true
          components: rustfmt, clippy
      - name: Install Node Dependencies
        run: yarn install
      - name: Build Binary
        run: yarn build:debug
      - name: Run Linting
        run: yarn lint:ts
      - name: Run Tests
        run: yarn test
      - name: Build JS
        run: yarn build:ts
